-- REQUERIMIENTO MADERA ALMACENADA
DROP PROCEDURE MADERA_ALMACENADA;

CREATE OR REPLACE PROCEDURE MADERA_ALMACENADA
IS
BEGIN
    DECLARE
        CURSOR MADERA IS
            SELECT * FROM LOTEMADERA L
            WHERE L.ESTADO = 'S'
            ORDER BY L.FECHA DESC;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('ID LOTE' || '     ' || 'FECHA LOTE' || '     ' || 'PESO ACTUAL' || '     ' || 'EMAIL PROV');
        FOR itemLote IN MADERA
        LOOP
            DBMS_OUTPUT.PUT_LINE(rpad(itemLote.IDLOTE,12) || rpad(itemLote.FECHA,15) || rpad(itemLote.PESOACTUAL,16) || rpad(itemLote.EMAILPROVEEDOR,20));
        END LOOP;
    END;
END;

EXECUTE MADERA_ALMACENADA();